permalink: /:categories/:title
pygments: true
markdown: kramdown

future: false
exclude: [ 'Gemfile', 'Gemfile.lock' ]

url: http://stevenkaras.github.io
description: "Random thoughts that have collected in the corners of Steven's mind"

name: BitRot
author: Steven Karas
google_plus: https://plus.google.com/+StevenKaras
production: true
analytics:
  enabled: true
  property_id: UA-46854062-1