permalink: /:categories/:title
pygments: true

future: false
exclude: [ 'Gemfile', 'Gemfile.lock' ]

url: http://stevenkaras.github.io

name: BitRot
author: Steven Karas
google_plus: https://plus.google.com/u/0/100357072133361657311