permalink: /:categories/:title/

future: false
exclude: [ 'Gemfile', 'Gemfile.lock', "Icon\r", "config.ru", "tmp", ]

url: http://blog.dev
description: "Random thoughts that have collected in the corners of Steven's mind"

name: BitRot
author: Steven Karas
google_plus: https://plus.google.com/+StevenKaras
production: false
analytics:
  enabled: false
  property_id: UA-46854062-1

kramdown:
  math_engine: null

defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
  -
    scope:
      path: ""
      type: drafts
    values:
      layout: post
